// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: updateUserCreds.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateUserCreds = `-- name: UpdateUserCreds :exec
UPDATE users
SET updated_at = NOW(), email = $2, hashed_password = $3
WHERE id = $1
`

type UpdateUserCredsParams struct {
	ID             uuid.UUID `json:"id"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
}

func (q *Queries) UpdateUserCreds(ctx context.Context, arg UpdateUserCredsParams) error {
	_, err := q.db.ExecContext(ctx, updateUserCreds, arg.ID, arg.Email, arg.HashedPassword)
	return err
}
